### ISSUE TITLE
No audio when launching game through Steam

### ISSUE THREAD

**Issue by ghost** [Orochimarufan/Kawariki#4]
When launching Lost Chapter on Steam using Kawariki 2.0 as the compatibility tool the game runs fine but no audio plays. After disabling Steamworks integration and launching with `Kawariki run Game.exe` audio works as expected, though obviously I don't get playtime, achievements, etc. Not sure how to go about troubleshooting this further, open to suggestions if they would help with debugging. Feel free to close if this is more likely to be an issue with my setup rather than Kawariki.

**Game:** [Lost Chapter](https://store.steampowered.com/app/2356470/) (NSFW)
**Runtime:** NW.js (MZ 1.4.0)
**System Info:** Arch Linux - latest PipeWire, Steam, and Kawariki

edit: Some extra info
- I don't have this issue with other games using Kawariki (though this is the only MZ game in my library).
- Nothing of note when comparing terminal output of running through Steam vs. not.
- When launching through Steam, 2 audio applications/outputs labeled Chromium appear. They're using the correct output device, but no audio ever plays and they disappear a short while later.
- When launching outside of Steam, 2 audio applications/outputs labeled Chromium appear. Audio plays out of one of them and the other disappears a short while later.

**Comment by Orochimarufan** [comment]
Have you looked at the devtools console? `KAWARIKI_SDK=1 KAWARIKI_NWJS_DEVTOOLS=1` It may give you more clues as to what is going on.
My only guess is something to do with all the containerization going on when launching things through steam these days.
